In [2]:
import numpy as np
import pandas as pd
import random

##### [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)

In [10]:
arr = np.arange(16).reshape(2, 2, 4)
print(arr, arr.shape, '\n\n')

arr1 = np.transpose(arr, (1, 0, 2))
print(arr1, arr1.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 


[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


##### [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요(shape 확인)

In [32]:
arr2 = np.transpose(arr, (0, 2, 1))
print(arr2, arr2.shape)
print()
arr3 = np.swapaxes(arr, 2, 1)
print(arr3, arr3.shape)

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)


##### [과제] np.ones((5, 5))를 아래와 같이 출력하세요

In [27]:
zero1 = np.zeros((2, 5))
zero2 = np.zeros((9, 2))
one = np.ones((5, 5))

new = np.vstack([zero1, one, zero1])
new = np.hstack([zero2, new, zero2])
print(new)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
a=np.ones((5,5))
b=np.zeros((9,9))
b[2:7,2:7]=a
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
a = np.ones((5,5))
np.pad(a,(2,2)) #pad 배열에 ()형식으로 0을 추가

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

##### [과제] np.zeros((8, 8))을 아래와 같이 출력하세요.

In [5]:
zero = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        if i % 2 == 0 and j % 2 == 1:
            zero[i, j] = 1
        elif i % 2 == 1 and j % 2 == 0:
            zero[i, j] = 1
            
print(zero)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [41]:
a = np.array([[0,1],[1,0]])
b = np.tile(a,(4,4))
print(b)

x = np.zeros((8,8))
x[::2, 1::2] = 1 # (행 처음부터 끝가지 2칸 간격, 열 1부터 끝까지 2칸 간격)
x[1::2, ::2] = 1 # 
x

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

##### [과제] np.arange(336).reshape(6, 7, 8)에서 100번째 요소의 인덱스를 구하세요

In [47]:
a = np.arange(336).reshape(6, 7, 8)

print(np.where(a == 99))

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


In [46]:
arr = np.arange(336).reshape(6,7,8)
print(arr)
print(np.unravel_index(99,(6,7,8)))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

##### [과제] np.arange(4)를 이용해서 아래와 같이 출력하세요

In [48]:
zero = np.zeros((5, 5))
a = np.arange(4)

for i in range(4):
    zero[i + 1, i] = a[i] + 1
    
print(zero)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [10]:
arr = np.arange(4)
print(np.diag(arr + 1, k = -2))
print()
print(np.diag(arr + 1, k = 2))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]

[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


np.diag 설명 : https://studymake.tistory.com/425

##### [과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요 (관측치 1000개) - 관측치 : 행의 개수
- id : 1 ~ 1000번 일련번호
- gender : 0, 1 정수 난수 생성
- age : 0 ~ 80 사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111 ~ 99999
- product_20 : 제품코드 11111 ~ 99999
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년 구매금액이 증가면 1, 감소면 0

In [25]:
# 제품코드랑 가격연동

import numpy as np
import pandas as pd
import random

frame = np.zeros((len(index), len(columns)))
columns = ['Id', 'Gender', 'Age', 'Region', 'Product_19', 'Product_20', 'Price_19', 'Price_20', 'Quantity_19', 'Quantity_20', 'Time_19', 'Time_20', 'Amount_19', 'Amount_20', 'Sales']
index = range(1, 1001)
df = pd.DataFrame(frame, index, columns)

Product = np.random.randint(11111, 100000, 1000)
Price = np.round(np.random.uniform(1000, 50000, 1000), 3)
Product_Price = list(zip(Product, Price))
Product_Price = np.array(Product_Price)

df.Id = np.arange(1, 1001)
df.Gender = np.random.randint(2, size = 1000)
df.Age = np.random.randint(1, 81, 1000)
df.Region = np.random.randint(1, 10, 1000)
df.Product_19 = Product_Price[:, 0].astype(int)
df.Product_20 = Product_Price[:, 0].astype(int)
df.Price_19 = Product_Price[:, 1]
df.Price_20 = Product_Price[:, 1]
df.Quantity_19 = np.random.randint(1, 101, 1000)
df.Quantity_20 = np.random.randint(1, 101, 1000)
df.Time_19 = np.random.randint(1, 25, 1000)
df.Time_20 = np.random.randint(1, 25, 1000)
df.Amount_19 = df.apply(lambda x: x['Price_19'] * x['Quantity_19'], axis = 1)
df.Amount_20 = df.apply(lambda x: x['Price_20'] * x['Quantity_20'], axis = 1)
df.Sales = np.where(df.Amount_20 > df.Amount_19, 1, 0)

df

Id  Gender  Age  Region  Product_19  Product_20   Price_19   Price_20  \
1        1       0   11       8       32933       32933  32577.601  32577.601   
2        2       1   20       3       45009       45009  39917.492  39917.492   
3        3       1   36       8       68670       68670  36847.482  36847.482   
4        4       1   76       3       51193       51193  34362.087  34362.087   
5        5       1   69       7       64353       64353  21456.412  21456.412   
...    ...     ...  ...     ...         ...         ...        ...        ...   
996    996       1   15       7       73535       73535  37697.573  37697.573   
997    997       0   35       4       26262       26262  41498.300  41498.300   
998    998       0   15       5       26116       26116  21613.389  21613.389   
999    999       1   80       8       58590       58590   9249.663   9249.663   
1000  1000       0    6       7       92904       92904  11060.832  11060.832   

      Quantity_19  Quantity_20  Time_19  Time_20    Amount_19    Amount_20  \
1              50           76       24        8  1628880.050  2475897.676   
2               8           72       24       11   319339.936  2874059.424   
3              51            7       19        6  1879221.582   257932.374   
4              54           34        5       14  1855552.698  1168310.958   
5              69           79       10        2  1480492.428  1695056.548   
...           ...          ...      ...      ...          ...          ...   
996            49           68       12       11  1847181.077  2563434.964   
997            86           87       23        1  3568853.800  3610352.100   
998            48           79       10       15  1037442.672  1707457.731   
999            47           17        9       10   434734.161   157244.271   
1000           28           47       11        2   309703.296   519859.104   

      Sales  
1         1  
2         1  
3         0  
4         0  
5         1  
...     ...  
996       1  
997       1  
998       1  
999       0  
1000      1  

[1000 rows x 15 columns]

In [38]:
print(df[df.Sales == 0])
print()
print(len(df[df.Sales == 0]))
# df[df.Sales == 1]

      Id  Gender  Age  Region  Product_19  Product_20   Price_19   Price_20  \
3      3       1   36       8       68670       68670  36847.482  36847.482   
4      4       1   76       3       51193       51193  34362.087  34362.087   
7      7       0   12       8       82468       82468  30831.071  30831.071   
12    12       1   11       9       51915       51915  48002.566  48002.566   
15    15       0   13       6       64118       64118  15032.013  15032.013   
..   ...     ...  ...     ...         ...         ...        ...        ...   
986  986       0   18       2       69252       69252  43694.236  43694.236   
990  990       0   16       2       21915       21915  11917.047  11917.047   
991  991       0   75       6       63099       63099   4046.374   4046.374   
995  995       1   29       8       47632       47632  39720.132  39720.132   
999  999       1   80       8       58590       58590   9249.663   9249.663   

     Quantity_19  Quantity_20  Time_19  Time_20    

In [55]:
import numpy as np
import pandas as pd

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(11111,100000,size = customer)
df.product_20 = np.random.randint(11111,100000,size = customer)

pricearray= np.random.randint(10,500,size = 100000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df

C:\Users\spiner\AppData\Local\Temp/ipykernel_12348/3487086647.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.price_19[i] = pricearray[df.product_19[i]]
C:\Users\spiner\AppData\Local\Temp/ipykernel_12348/3487086647.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.price_20[i] = pricearray[df.product_20[i]]
C:\Users\spiner\AppData\Local\Temp/ipykernel_12348/3487086647.py:34: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df

id gender  age  product_19  product_20  price_19  price_20  \
1        1      M   40       24227       55976     42900     17000   
2        2      F   29       77462       78920     27400     38500   
3        3      F   25       53750       46507     25600     49500   
4        4      M   19       73611       29381     28000     19100   
5        5      F   68       82728       84075      1300     23200   
...    ...    ...  ...         ...         ...       ...       ...   
996    996      M   24       73435       97517      6400     21300   
997    997      M   53       36781       83820     34400     21600   
998    998      M   24       38495       96299     12700      7700   
999    999      F   73       56675       61737     15700     21000   
1000  1000      M   42       88153       76382     10100     32500   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              76           79       18       20    3260400    1343000      0  
2              66           45        4       19    1808400    1732500      0  
3              55           36       24       18    1408000    1782000      1  
4              71           15        2       17    1988000     286500      0  
5              20           90        3       20      26000    2088000      1  
...           ...          ...      ...      ...        ...        ...    ...  
996             7           76       20       10      44800    1618800      1  
997            28           53       10       24     963200    1144800      1  
998            72           35        8        7     914400     269500      0  
999            54            6        1       17     847800     126000      0  
1000           56           39       13       23     565600    1267500      1  

[1000 rows x 14 columns]

In [27]:
Product = np.random.randint(11111, 100000, 1000)
Price = np.round(np.random.uniform(1000, 50000, 1000), 3)

Product_Price = list(zip(Product, Price))
Product_Price = np.array(Product_Price)

print(Product_Price)

[[82311.    32588.949]
 [65852.    39381.011]
 [71835.    20948.503]
 ...
 [79066.     1098.749]
 [16752.    32089.732]
 [16670.    23838.943]]
