##### [과제] 1변량 데이터 data에 대하여 평균, 표본 분산, 불편 분산, 표준 편차, 최대, 최소, 4분위수, 중앙값을 구하세요
##### 단, 함수사용하는 경우와 사용하지 않는 경우를 모두 수행하세요

In [39]:
import pandas as pd
import numpy as np

In [40]:
data = np.array([2,3,3,4,4,4,4,5,5,6])

In [41]:
# 평균

total = 0
for i in range(len(data)):
    total += data[i]
print(total / len(data))

print(data.mean(), '\n')

4.0
4.0 



In [42]:
# 중앙값

n = len(data)
if n % 2 == 0:
    m0 = data[n // 2 - 1]
    m1 = data[n // 2]
    median = (m0 + m1) / 2
else:
    median = data[n // 2]
print(median, '\n')

print(np.median(data))

4.0 

4.0


In [43]:
# 최대, 최소

print(sorted(data)[-1])
print(data.max(), '\n')

print(sorted(data)[0])
print(data.min(), '\n')

6
6 

2
2 



In [44]:
# 4분위수

if n % 2 == 0:
    data_Q1 = data[0:n // 2 - 1].sum() / 2
    data_Q3 = data[n // 2:].sum() / 2
    
print(data_Q1)
print(data_Q1, data_Q3, '\n')

np.percentile(data, [25, 75])

6.0
6.0 12.0 



array([3.25, 4.75])

In [48]:
# 표본 분산

deviation = data - np.mean(data) # 편차
print(np.mean(deviation ** 2), '\n')

print(np.var(data, ddof = 0))

1.2 

1.2


In [46]:
# 불편 분산

deviation = data - np.mean(data)
print(np.sum(deviation ** 2) / (len(deviation) - 1), '\n')

print(np.var(data, ddof = 1))

1.3333333333333333 

1.3333333333333333


In [38]:
# 표준 편차

std_div = np.var(data) ** (1/2) # 분산의 제곱근
print(std_div, '\n')

print(np.std(data))

33.04254832787568 

33.04254832787568


##### [과제] 2행 10열 2차원 배열을 생성하고 두열간의 공분산 및 상관계수를 구하세요(단, numpy, pandas 두가지 방식으로 모두 수행)

In [25]:
data = np.random.randint(100, size = (2, 10))
data

array([[14, 14, 59, 73, 32, 43, 89, 85, 82, 75],
       [16, 98, 30,  6, 99, 52,  9, 17,  2, 19]])

In [26]:
# 공분산

dev0 = data[0] - data[0].mean()
dev1 = data[1] - data[1].mean()

print(dev0)
print(dev1, '\n')

cov = (dev0 * dev1).sum() / (len(dev0) - 1)
cov.astype(float)
print(cov, '\n') # 공분산
print(cov / (np.std(data[0]) * np.std(data[1]))) # 상관계수

[-42.6 -42.6   2.4  16.4 -24.6 -13.6  32.4  28.4  25.4  18.4]
[-18.8  63.2  -4.8 -28.8  64.2  17.2 -25.8 -17.8 -32.8 -15.8] 

-739.3111111111111 

-0.7799428435006216


In [27]:
cov_mat = np.cov(data[0], data[1])
cov_mat
corr = np.corrcoef(data[0], data[1])
print(cov_mat[0, 1], '\n') # 공분산
print(corr[0, 1]) # 상관계수

-739.3111111111111 

-0.7019485591505594


In [30]:
data0 = pd.DataFrame(data[0])
data1 = pd.DataFrame(data[1])

df = pd.concat([data0, data1], axis = 1)
df.columns = ['data0', 'data1']
df

display(df.cov())
display(df.corr())

data0        data1
data0  837.155556  -739.311111
data1 -739.311111  1325.066667

data0     data1
data0  1.000000 -0.701949
data1 -0.701949  1.000000