In [175]:
import numpy as np
import pandas as pd

# [2월 28일]
---

## # numpy 복습
---

In [13]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [2, 3, 4]])
array3 = np.array([[[1, 2, 3]]])

print(array1, array1.shape)
print(array2, array2.shape)
print(array3, array3.shape)

[1 2 3] (3,)
[[1 2 3]
 [2 3 4]] (2, 3)
[[[1 2 3]]] (1, 1, 3)


In [23]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float.dtype)

array_int2 = array_float.astype('int32')
print(array_int2.dtype)

float64
int32


In [37]:
zero_array = np.zeros((3, 2))
zero_array
print(zero_array, zero_array.dtype, '\n')

zero_array = np.zeros((3, 2)).astype(int)
zero_array
print(zero_array, zero_array.dtype, '\n')

zero_array = np.zeros((3, 2), dtype = 'int8')
zero_array
print(zero_array, zero_array.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]] float64 

[[0 0]
 [0 0]
 [0 0]] int32 

[[0 0]
 [0 0]
 [0 0]] int8


### # reshape
---

In [57]:
ar1 = np.arange(10)
ar2 = ar1.reshape(5, 2)
ar3 = ar1.reshape(2, 1, -1)

display(ar1, ar2, ar3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [66]:
# 3차원 -> 2, 1차원

ar3 = np.arange(8).reshape((2, 2, 2))
ar2 = ar3.reshape(2, 4)
ar1 = ar3.reshape(-1)

display(ar3, ar2, ar1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([0, 1, 2, 3, 4, 5, 6, 7])

### # indexing
---

In [72]:
ar1 = np.arange(1, 10)
print(ar1, '\n')

print(ar1[1], ar1[-1], ar1[-3])

[1 2 3 4 5 6 7 8 9] 

2 9 7


In [84]:
ar2d = np.arange(1, 10).reshape(3, 3)
print(ar2d, '\n')

print(ar2d[0,0], ar2d[0,1], ar2d[1, 0], ar2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

1 2 4 9


### # slicing
---

In [92]:
ar1 = np.arange(1, 20)
print(ar1, '\n')

print(ar1[3:6])
print(ar1[-16:-13])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[4 5 6]
[4 5 6]


In [117]:
ar2d = np.arange(1, 10).reshape(3, 3)
print(ar2d, '\n')

print(ar2d[0:2, 0:2], '\n')
print(ar2d[1:, 0:], '\n')
print(ar2d[:2, 1:3], '\n')
print(ar2d[:2,:1], '\n')
print(ar2d[:2,0], '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2]
 [4 5]] 

[[4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]] 

[[1]
 [4]] 

[1 4] 



### # boolean indexing
---

In [128]:
ar1 = np.arange(1, 10)
print(ar1, '\n\n')

print(np.where(ar1 > 5), '\n')
print(ar1[ar1 > 5], '\n')

[1 2 3 4 5 6 7 8 9] 


(array([5, 6, 7, 8], dtype=int64),) 

[6 7 8 9] 



### # fancy indexing
---

In [136]:
ar1 = np.arange(1, 10).reshape(3, 3)
print(ar1, '\n\n')

print(ar1[[0, 1], 2], '\n')
print(ar1[[0, 1], :2], '\n')
print(ar1[[0, 1]], '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 


[3 6] 

[[1 2]
 [4 5]] 

[[1 2 3]
 [4 5 6]] 



### # sort
---

In [146]:
ar = np.array([3, 1, 9, 5])
print(ar, '\n\n')

# np.sort() : 원본 미반영
sort_ar = np.sort(ar)
print(sort_ar)
print(ar, '\n')

# ndarray.sort() : 원본 반영
sort_ar1 = ar.sort()
print(sort_ar1)
print(ar, '\n')

[3 1 9 5] 


[1 3 5 9]
[3 1 9 5] 

None
[1 3 5 9] 



In [148]:
# 내림차순

sort_ar_desc = np.sort(ar)[::-1]
print(sort_ar_desc)

[9 5 3 1]


In [152]:
# 2차원 정렬

ar2 = np.array([[8, 12],
               [7, 1]])
print(ar2, '\n\n')

sort_ar2_axis0 = np.sort(ar2, axis = 0)
print(sort_ar2_axis0, '\n')

sort_ar2_axis1 = np.sort(ar2, axis = 1)
print(sort_ar2_axis1)

[[ 8 12]
 [ 7  1]] 


[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [168]:
# 정렬 행렬의 인덱스 반환

ar = np.array([3, 1, 9, 5])
print(ar, '\n\n')

sort_indices = np.argsort(ar)
print(sort_indices)

[3 1 9 5] 


[1 0 3 2]


### # 행렬 내적
---

In [169]:
a = np.array([[1, 2, 3],
            [4, 5, 6]])
b = np.array([[7, 8],
            [9, 10],
            [11, 12]])

np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

### # 전치 행렬
---

In [174]:
a = np.array([[1, 2,],
             [3, 4]])

a.transpose()
a.T

array([[1, 3],
       [2, 4]])

## # pandas 복습
---
- ./경로 : 현재 폴더에서 불러오기
- ../경로 : 상위 폴더로 넘어가서 불러오기

In [182]:
t_df = pd.read_csv('../data/train.csv')

In [290]:
display(t_df.head())
display(t_df.shape)
display(t_df.describe())

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

(891, 12)

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

KeyError: "None of [Index(['Ticket'], dtype='object')] are in the [index]"

In [193]:
t_df.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

### # 데이터프레임과 리스트, 딕셔너리, 배열의 상호 변환
---

In [203]:
col_name1 = ['col1']
list1 = [1, 2, 3]
ar1 = np.array(list1)

df = pd.DataFrame(data = ar1, columns = col_name1)
df1 = pd.DataFrame(data = list1, columns = col_name1)
display(df, df1)

col1
0     1
1     2
2     3

col1
0     1
1     2
2     3

In [305]:
dict_ = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
df_dict_ = pd.DataFrame(dict_)
display(df_dict_)

a = df_dict_.values.tolist() 
b = df_dict_.to_dict()
c = df_dict_.values
print(a, '\n')
print(b, '\n')
print(c)

col1  col2  col3
0     1     2     3
1    11    22    33

[[1, 2, 3], [11, 22, 33]] 

{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}} 

[[ 1  2  3]
 [11 22 33]]


### # 데이터프레임 수정
---

In [328]:
t_df['Age_0'] = 0
t_df['Age_10'] = t_df['Age'] * 10
t_df['Family'] = t_df.SibSp + t_df.Parch
display(t_df.head())
# t_df.drop(t_df[['Age_10', "Age_0", 'Family']], axis = 1)
# t_df.drop(['Age_10', "Age_0", 'Family'], axis = 1, inplace = True)
t_df.drop(['Age_10', "Age_0", 'Family'], axis = 1).head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_10  Age_0  Family  
0      0         A/5 21171   7.2500   NaN        S   220.0      0       1  
1      0          PC 17599  71.2833   C85        C   380.0      0       1  
2      0  STON/O2. 3101282   7.9250   NaN        S   260.0      0       0  
3      0            113803  53.1000  C123        S   350.0      0       1  
4      0            373450   8.0500   NaN        S   350.0      0       0

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [347]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth',10)
t_df.head(2)

PassengerId  Survived  Pclass       Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked  Age_10  Age_0  Family
0          1           0       3  Braund...    male  22.0      1      0  A/5 21171   7.2500   NaN        S   220.0      0       1
1          2           1       1  Cuming...  female  38.0      1      0   PC 17599  71.2833   C85        C   380.0      0       1

In [379]:
v_counts = t_df.Pclass.value_counts()
print(type(v_counts))

display(v_counts)
new_v_counts = v_counts.reset_index(inplace = False)
display(new_v_counts)
display(new_v_counts.reset_index())
display(new_v_counts.reset_index(drop = True))
new_v_counts.set_index('index')

<class 'pandas.core.series.Series'>


3    491
1    216
2    184
Name: Pclass, dtype: int64

index  Pclass
0      3     491
1      1     216
2      2     184

level_0  index  Pclass
0        0      3     491
1        1      1     216
2        2      2     184

index  Pclass
0      3     491
1      1     216
2      2     184

Pclass
index        
3         491
1         216
2         184

In [376]:
# 여성중 pclass 1이면서 생존한 승객만 출력

display(t_df[t_df.Pclass == 3].head())
display(t_df[(t_df['Pclass'] == 1) & (t_df['Survived'] == 1) & (t_df['Sex'] == 'female')].head())

PassengerId  Survived  Pclass       Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked  Age_10  Age_0  Family
0          1           0       3  Braund...    male  22.0      1      0  A/5 21171   7.2500   NaN        S   220.0      0       1
2          3           1       3  Heikki...  female  26.0      0      0  STON/O...   7.9250   NaN        S   260.0      0       0
4          5           0       3  Allen,...    male  35.0      0      0     373450   8.0500   NaN        S   350.0      0       0
5          6           0       3  Moran,...    male   NaN      0      0     330877   8.4583   NaN        Q     NaN      0       0
7          8           0       3  Palsso...    male   2.0      3      1     349909  21.0750   NaN        S    20.0      0       4

PassengerId  Survived  Pclass       Name     Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  Age_10  Age_0  Family
1           2           1       1  Cuming...  female  38.0      1      0  PC 17599   71.2833   C85        C   380.0      0       1
3           4           1       1  Futrel...  female  35.0      1      0    113803   53.1000  C123        S   350.0      0       1
11         12           1       1  Bonnel...  female  58.0      0      0    113783   26.5500  C103        S   580.0      0       0
31         32           1       1  Spence...  female   NaN      1      0  PC 17569  146.5208   B78        C     NaN      0       1
52         53           1       1  Harper...  female  49.0      1      0  PC 17572   76.7292   D33        C   490.0      0       1